Update pogs paralogs
abims-sbr/adaptsearch_old pull request #19
Opened 2017-07-10 10:10 UTC by Mataivic

Managed to mix no_zip version and paralogous_filtering version

2017-07-11 13:43 UTC, lecorguille requested changes

2017-07-11 13:43 UTC, lecorguille commented on galaxy_wrappers/03_POGs/README.md
> +Version 1.1 - 03/05/2017
Le tool est en version 2.0
Et synchronise avec ce que tu as en fin de `<help>`

2017-07-11 13:43 UTC, lecorguille commented on galaxy_wrappers/03_POGs/POGs.xml
> +		python $__tool_directory__/scripts/S01_get_locus_orthologs_part1.py $infiles_from_paiwise_prot
Est-ce que tu peux encadrer le nom les noms de scripts et toutes les noms de fichiers `$infiles_from_paiwise_prot` par des `'` ?

2017-07-11 13:43 UTC, lecorguille commented on galaxy_wrappers/03_POGs/POGs.xml
> +		python $__tool_directory__/scripts/S02_get_locus_orthologs_part2.py $infiles_from_filter_assembly $minseq $paralogs
Idem

2017-07-11 14:30 UTC, Mataivic commented on galaxy_wrappers/03_POGs/POGs.xml
> +		python $__tool_directory__/scripts/S02_get_locus_orthologs_part2.py $infiles_from_filter_assembly $minseq $paralogs
Comme ça ?:

`python '$__tool_directory__/scripts/S01_get_locus_orthologs_part1.py' '$infiles_from_paiwise_prot'`

`python '$__tool_directory__/scripts/S02_get_locus_orthologs_part2.py' '$infiles_from_filter_assembly' $minseq $paralogs`

2017-07-12 09:07 UTC, lecorguille commented on galaxy_wrappers/03_POGs/POGs.xml
> +		python $__tool_directory__/scripts/S02_get_locus_orthologs_part2.py $infiles_from_filter_assembly $minseq $paralogs
Yes
En gros, il faut qu'on fasse le tour de tous les wrappers pour protéger les string (pour éviter l’insertion de code malin) et les paths (si il y a des espaces)

2017-07-12 12:42 UTC, lecorguille approved these changes

2017-07-12 12:43 UTC, lecorguille approved these changes

2017-07-12 13:05 UTC, merged