Update orthogroups tool
abims-sbr/adaptsearch_old pull request #30
Opened 2017-12-05 16:31 UTC by Mataivic

Outil post-orthofinder adapté aux headers de TransDecoder sur GalaxyDev

2017-12-11 10:29 UTC, lecorguille requested changes

2017-12-11 10:29 UTC, lecorguille commented on galaxy_wrappers/Reformat_Transdecoder/scripts/oneLine.py~
> +#!/usr/bin/env python
Est-ce que tu pourrais supprimer ce fichier ?
Et voir ajouter un pattern à propos de ces fichiers dans le fichier .gitignore

2017-12-11 10:29 UTC, lecorguille commented on scripts/Reformat_Transdecoder/oneLine.py
> +    seqOneLine(sys.argv[1], sys.argv[2])
Utilise argparse systématiquement

2017-12-11 10:29 UTC, lecorguille commented on scripts/Reformat_Transdecoder/oneLine.py
> +
Un peu de documentation sur ce que fait le script s'impose

2017-12-11 10:29 UTC, lecorguille commented on scripts/03b_Orthogroups_Tool/format_transdecoder_headers.sh
> +sed -i -E 's/OG[0-9]{7,}:\s//' $1
Tu sais que `sed -i` modifie le fichier directement ... donc si je te suis bien le fichier rentrée en input de ton outil.
Il te faut un fichier temporaire

2017-12-11 10:29 UTC, lecorguille commented on galaxy_wrappers/03b_Orthogroups_Tool/orthogroups_tool.xml
> +            <param name="nbseq" value="2"/>
Est-ce juste pour réduire le temps du test ?

2017-12-11 10:29 UTC, lecorguille commented on galaxy_wrappers/03b_Orthogroups_Tool/orthogroups_tool.xml
> +            <param name="inputs_fasta" value="output_filterassemblies/AcAcaud_trinity.fasta,output_filterassemblies/AmAmphi_trinity.fasta,output_filterassemblies/ApApomp_trinity.fasta,output_filteras
Il y a beaucoup de fichiers dans test-data au regarde de ce que tu utilises dans ton unique test

2018-01-11 13:01 UTC, Mataivic commented
@lecorguille J'ai appliqué les 'requested changes'

2018-01-12 12:36 UTC, lecorguille approved these changes

2018-01-12 12:51 UTC, merged