Correc mutcount
abims-sbr/adaptsearch_old pull request #31
Opened 2017-12-05 17:01 UTC by Mataivic

Correction bug dans les script d'Eric de MutCount (tableaux de données de sortie faux)

2017-12-11 10:34 UTC, lecorguille requested changes

2017-12-11 10:34 UTC, lecorguille commented on galaxy_wrappers/07_MutCount/scripts/S01b_study_seq_composition_aa.py~
> +#!/usr/bin/env python
A supprimer
Ajoute le pattern `*~` dans ton `.gitignore`

2017-12-11 10:34 UTC, lecorguille commented on galaxy_wrappers/07_MutCount/scripts/S02b_study_seq_composition_nuc.py~
> +#!/usr/bin/env python
A supprimer

2017-12-11 10:34 UTC, lecorguille commented on scripts/Reformat_Transdecoder/oneLine.py
> +#!/usr/bin/env python
Tu as intègre dans ton PR des commits qui n'ont rien à voir :/

2017-12-11 10:35 UTC, lecorguille commented
Un rebase s'impose pour virer les commits qui concernent Reformat_Transdecoder
Et un bon menage dans les `*~`

2017-12-11 11:48 UTC, Mataivic commented on scripts/Reformat_Transdecoder/oneLine.py
> +#!/usr/bin/env python
Mince j'ai pas fait gaffe (commit sur la mauvaise branche). Je corrigerai.

2018-01-11 13:01 UTC, Mataivic commented
@lecorguille J'ai appliqué les 'requested changes'

2018-01-12 12:36 UTC, lecorguille approved these changes

2018-01-12 12:51 UTC, merged