Use list file
abims-sbr/adaptsearch_old pull request #41
Opened 2018-06-14 09:15 UTC by Mataivic

- Modification des lignes de commande des outils les plus en aval: au lieu d'avoir `./script.py file1,file2,file3,file4,...'`, on a désormais `./script.py list_file`, où `list_file` est un fichier texte contenant le nom de tous les fichiers d'entrée

- Cette approche est mise en place suite à un bug de Didier où, apriori, le nombre de fichiers d'entrée très élevé a fait planter l'interpréteur Python (dépassement du nombre maximal de caractères autorisés dans une ligne de commande ?). J'ai d'abord utilisé `glob` (trois commits concernés), puis modifié à nouveau pour utiliser la méthode avec`list_file`

Autres petits changements :

- prise en charge des nucléotides 'N' dans CDS_Search (bug découvert par Stéphane)
- Mise à jour de Mutcount en mode concaténé : ajout du calcul du 'Substitution Exchangeability Disequilibrium' de Pierre-Guillaume + simplification du calcul de la pvalue

2018-06-25 14:56 UTC, lecorguille requested changes

2018-06-25 14:56 UTC, lecorguille commented on scripts/06_ConcatPhyl/S01_concatenate.py
> +import string, os, time, re, sys, itertools, glob
Do you still need `glob`?

2018-06-25 14:56 UTC, lecorguille commented on scripts/07_MutCount/S01b_study_seq_composition_aa.py
> +# infiles = glob.glob('*.fasta')
Can you clean up some of your comments or comment them if there are still interesting?

2018-06-25 14:56 UTC, lecorguille commented on scripts/07_MutCount/make_listfiles.py
> +
Please add some comments to explain what the script does

2018-06-25 14:56 UTC, lecorguille commented on scripts/06_ConcatPhyl/make_listfiles.py
> +
Please add some comments to explain what the script does

2018-06-25 14:56 UTC, lecorguille commented on scripts/07_MutCount/make_listfiles.py
> +
Is it the same as `scripts/06_ConcatPhyl/make_listfiles.py`?

2018-06-25 14:56 UTC, lecorguille commented on scripts/06_ConcatPhyl/S01_concatenate.py
> +#L_IN = str.split(input_alignments,",")
Clean up of the commented line if there aren't necessary anymore

2018-06-25 14:56 UTC, lecorguille commented on scripts/05_CDS_search/make_listfiles.py
> +
Is it the same as `scripts/06_ConcatPhyl/make_listfiles.py`and `scripts/07_MutCount/make_listfiles.py`?

2018-06-27 09:38 UTC, lecorguille commented on scripts/05_CDS_search/make_listfiles.py
> +
You didn't answer to me about those questions

2018-06-27 09:51 UTC, Mataivic commented on scripts/05_CDS_search/make_listfiles.py
> +
oops, sorry. Same scripts, but different files (copy-pasted in each tool).

2018-06-27 14:19 UTC, lecorguille commented on scripts/05_CDS_search/make_listfiles.py
> +
Can you deal with symbolic links?

2018-06-28 08:21 UTC, Mataivic commented on scripts/05_CDS_search/make_listfiles.py
> +
Done.

2018-06-29 11:45 UTC, lecorguille approved these changes

2018-06-29 11:45 UTC, merged

2018-06-29 11:45 UTC, lecorguille commented
Up to you to push on the ToolSheds